Repository akarzhaneuski/sandbox_jun2021, pull requests merged in 2021-06, with the labels that each got.

#21 fix save methods in controllers
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/BaseEntity.java
Labels: bug

#24 Fixed many-to-many connection.
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Company.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Discount.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Location.java
Labels: bug

#26 fix import
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Company.java
Labels: bug

#31 SearchCriteria
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/SearchCriteria.java
Labels: checkout, duplicate

#29 Added DiscountDTO.
  pom.xml
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/CompanyDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/DiscountDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/LocationDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/mapper/MapperConverter.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/DiscountService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/DiscountServiceImpl.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/Application.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/DiscountRestController.java
Labels: good first issue

#35 fixed import Review
  sandbox-web/src/main/java/com/exadel/sandbox/team5/DiscountRestController.java
Labels: bug

#36 Exception Handler
  sandbox-web/src/main/java/com/exadel/sandbox/team5/error/ApiError.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/error/RestExceptionHandler.java
  sandbox-web/src/main/resources/application.yml
Labels: enhancement

#38 Exception Handler
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/CompanyServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/DiscountServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/EmployeeDiscountImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/EmployeeServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/LocationServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/ReviewServiceImpl.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/error/RestExceptionHandler.java
Labels: fix

#47 #69 - add Country table
  sandbox-backend/src/main/resources/db/migration/V0000010__addCountry_table.sql
  sandbox-backend/src/main/resources/db/migration/V0000011__addCountry.sql
Labels: update

#52 Fixed bag with null in companies.
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/DiscountDto.java
Labels: bug

#54 update migration script
  sandbox-backend/src/main/resources/db/migration/V0000013__update_Discount_Location.sql
Labels: fix

#43 51 - Add QR
  pom.xml
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/BackendApplication.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/barcodes/QRCodeGenerator.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/mapper/MapperConverter.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/DiscountService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/DiscountServiceImpl.java
  sandbox-backend/src/main/resources/application.yml
  sandbox-backend/src/test/java/com/exadel/sandbox/team5/service/DiscountServiceTest.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/Application.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/controller/CompanyRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/controller/DiscountRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/controller/LocationRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/controller/ReviewRestController.java
  sandbox-web/src/main/resources/application.yml
Labels: question

#60 #86 - added Category
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Category.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Tag.java
  sandbox-backend/src/main/resources/db/migration/V0000016__addCategory.sql
Labels: refactored, update

#61 #110 - bag in search
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/DiscountDAO.java
Labels: bug, refactored

#59 #51 Fixed test in QR.
  pom.xml
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/barcodes/QRCode.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/DiscountService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/QRCodeService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/DiscountServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/QRCodeServiceImpl.java
  sandbox-backend/src/test/java/com/exadel/sandbox/team5/service/QRCodeTest.java
  sandbox-backend/src/test/java/resources/testQR1.png
  sandbox-web/src/main/java/com/exadel/sandbox/team5/Application.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/DiscountRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/TagRestController.java
Labels: fix

#58 #101 - refactored Location.
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/CompanyDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/LocationDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/DiscountDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/LocationDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Address.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/City.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Company.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Country.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Discount.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Employee.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Location.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/LocationService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/CompanyServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/LocationServiceImpl.java
  sandbox-backend/src/main/resources/db/migration/V0000015__refactor_Location.sql
  sandbox-web/src/main/java/com/exadel/sandbox/team5/LocationRestController.java
Labels: enhancement, refactored, update

#62 bug with migration
  sandbox-backend/src/main/resources/db/migration/V0000015__refactor_Location.sql
Labels: fix

#64 update Address
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Address.java
Labels: bug
