Repository akarzhaneuski/sandbox_jun2021, pull requests merged in 2021-07, with the labels that each got.

#63 56_Image s3v2.0
  sandbox-backend/pom.xml
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/ImageDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/DiscountDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/ImageDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Discount.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Image.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/ImageService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/ImageServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/AWSConfiguration.java
  sandbox-backend/src/main/resources/db/migration/V0000013__addImageTable.sql
  sandbox-web/src/main/java/com/exadel/sandbox/team5/ImageRestController.java
  sandbox-web/src/main/resources/application.yml
Labels: good first issue

#25 23_added security
  pom.xml
  sandbox-backend/pom.xml
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/EmployeeDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/EmployeeService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/EmployeeServiceImpl.java
  sandbox-backend/src/main/java/db/migration/V00000018__modifyPasswordEmployee.java
  sandbox-web/pom.xml
  sandbox-web/src/main/java/com/exadel/sandbox/team5/AuthenticateRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/config/security/AuthenticationService.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/config/security/AuthenticationServiceImpl.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/config/security/JwtRequestFilter.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/config/security/JwtUserDetailsService.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/config/security/SecurityConfigurer.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/config/security/pojo/AuthenticationRequest.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/config/security/pojo/Token.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/config/security/util/JwtUser.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/config/security/util/JwtUserFactory.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/config/security/util/JwtUtil.java
  sandbox-web/src/main/resources/application.yml
Labels: enhancement

#65 #82 - Add statistic
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/CompanyDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/DiscountDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/OrderDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/OrderDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/OrderService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/DiscountServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/OrderServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/CreateOrder.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/Pair.java
  sandbox-backend/src/main/resources/db/migration/V0000020__setCompany_to_Discount.sql
  sandbox-backend/src/main/resources/db/migration/V0000021__addOrders.sql
  sandbox-web/src/main/java/com/exadel/sandbox/team5/CompanyRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/DiscountRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/LocationRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/OrderRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/ReviewRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/TagRestController.java
Labels: enhancement, refactored

#72 87 - Implemented searching by location.
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/DiscountDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/EmployeeDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/DiscountDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Address.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Discount.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/DiscountServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/DiscountSearchCriteria.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/LocationSearchCriteria.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/QueryUtils.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/SearchCriteria.java
  sandbox-backend/src/main/resources/db/migration/V0000022__addAddressToDiscount.sql
Labels: good first issue

#70 #122 - add Category to Discount
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/CategoryDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/DiscountDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/TagDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Category.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Discount.java
  sandbox-backend/src/main/resources/db/migration/V0000023__update_Category.sql
Labels: refactored

#76 changed response entity Tag->TagDto
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/TagService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/TagServiceImpl.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/TagRestController.java
Labels: fix, refactored

#80 fixed problem with displaying only items with rate.
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/DiscountDAO.java
Labels: fix

#86 #104 - extends statistics
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/OrderDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/OrderService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/DiscountServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/OrderServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/Pair.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/OrderRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/TagRestController.java
Labels: enhancement, refactored, update

#101 #156 - fix cascade relationships
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Address.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Category.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Company.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Country.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Discount.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Tag.java
Labels: fix

#112 #141 - Mail service 2.0
  sandbox-backend/pom.xml
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/DiscountDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/EmployeeDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/EmployeeDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Discount.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Employee.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/MailSenderService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/MailSenderServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/job/SubscriptionScheduler.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/Notification.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/Pair.java
  sandbox-backend/src/main/resources/db/migration/V0000029__addEmails_Subscriptions.sql
  sandbox-backend/src/main/resources/template/UI_mail.ftl
  sandbox-backend/src/main/resources/template/UI_notification.ftl
  sandbox-web/src/main/java/com/exadel/sandbox/team5/MailSenderRestController.java
  sandbox-web/src/main/resources/application.yml
Labels: enhancement, refactored

#120 fix yml
  sandbox-web/src/main/resources/application.yml
Labels: fix

#146 #205 - add Favorites
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/CategoryDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dao/DiscountDAO.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/EmployeeDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/entity/Employee.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/EmployeeService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/EmployeeServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/OrderServiceImpl.java
  sandbox-backend/src/main/resources/db/migration/V0000033__addFavoritesToEmployee.sql
  sandbox-web/src/main/java/com/exadel/sandbox/team5/EmployeeRestController.java
Labels: enhancement

#155 #206 - remove DELETE endpoints
  sandbox-web/src/main/java/com/exadel/sandbox/team5/CategoryRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/CompanyRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/DiscountRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/LocationRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/OrderRestController.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/ReviewRestController.java
Labels: update

#156 #141 - AWS SNS
  sandbox-backend/pom.xml
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/dto/DiscountDto.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/NotificationService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/DiscountServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/MailSenderServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/NotificationServiceImpl.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/AWSConfiguration.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/util/Message.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/MailSenderRestController.java
  sandbox-web/src/main/resources/application.yml
Labels: enhancement

#168 refactored EmployeeRestController
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/EmployeeService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/EmployeeServiceImpl.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/EmployeeRestController.java
Labels: refactored

#169 add getSubscriptions endpoint
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/EmployeeService.java
  sandbox-backend/src/main/java/com/exadel/sandbox/team5/service/impl/EmployeeServiceImpl.java
  sandbox-web/src/main/java/com/exadel/sandbox/team5/EmployeeRestController.java
Labels: update
